### ISSUE TITLE
Light without brightness

### ISSUE THREAD

**Issue by florisheyvaert** [nicufarmache/lovelace-big-slider-card#14]
Hello, 

Trying to use this template for a light without brightness control. So the light just turn on/off. 
Button works, but the state is not displayed correctly when turned on. 

The 'big-slider-card' gets following css classes
`
--bsc-percent:NaN%; --bsc-icon-color:var(--bsc-color); --bsc-brightness:0%; --bsc-brightness-ui:50%;
`
So it seems the light is turned off.

**Comment by nicufarmache** [comment]
Hey,

Thanks for letting me know. 
I never tested it on lights without brightness control. :grin:
I'll try to fix in in the text version

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
I came to report the same bug. Glad to see it's on your radar.

On a related note, would you consider adding the colorize functionality to lights without color control? For example, I have a bunch of phillips hue bulbs with variations in color temp (kelvin). I have another group of lights within the same menu that are statically set at 2700K color temp. In my UI, the Phillips hue in their default state show up in the big-slider-card with the color #ffa856 due to the colorize option, however the other lights show up as the default theme color. As a workaround I have manually set color to #ffa856, but the icon doesn't respond in kind. It would be useful for the sake of uniformity to perhaps allow in whatever way you think would be best, a way to match the colorize option for statically colored lights to match rgb/kelvin lights.

**Comment by nicufarmache** [comment]
@florisheyvaert 
I fixed the value and color issues and it works now. The only problem is that it still acts line a slider and you can slide it even though it eventually snaps to 100% or off. 

I was thinking to somehow detect the capability of the light and disable the sliding if needed but i have to look more into it because it's not as simple as I thought.  Maybe I'll implement this in a later version.


@zsQ8ymRSY8B4owpdCvTRdkz8rQUK 
I now added the `icon_color` option so now you can also hardcode the color of the icon

**Comment by florisheyvaert** [comment]
verified this & it's working, thanks!
