### ISSUE TITLE
Support for Section view

### ISSUE THREAD

**Issue by francesconazzaro** [nicufarmache/lovelace-big-slider-card#58]
Home Assistant has recently introduced Sections. Cards in a section can fill 1 or 2 columns. big-slider-card always fills 2 columns.

It would be great if the size of the big-slider-card could be customisable.

Here is a screenshot of the current behaviour

![image](https://github.com/nicufarmache/lovelace-big-slider-card/assets/9554021/9f3c8d9a-968f-4d4b-a400-b544157fb586)

**Comment by MangoScango** [comment]
It's a little janky, but I was able to do force this on 2024.07 with the new card resizing feature, by appending the following:

``` yaml
layout_options:
  grid_columns: 2
  grid_rows: 1
```

**Comment by francesconazzaro** [comment]
Thank you! This solution works. I'll close the issue

**Comment by xvlw** [comment]
Another way I made this work was to add the card to a horizontal stack and then modify the size through the new card resizing feature to half the width.

I think the card loses the ability to be modified directly in the UI via the new card resizing features due to it not having access to the visual editor.

I see PR 54 was added in February, hopefully this eventually allows the card to take advantage of the new HA UI settings they implemented.

https://github.com/nicufarmache/lovelace-big-slider-card/pull/54
